version: '3'

services:
  web:
    build: .
    ports:
      - "${PORT:-5000}:5000"
    environment:
      # Database configuration
      - DATABASE_URL=${DATABASE_URL:-postgresql://postgres:postgres@db:5432/videoshare}
      - PGUSER=${PGUSER:-postgres}
      - PGPASSWORD=${PGPASSWORD:-postgres}
      - PGHOST=${PGHOST:-db}
      - PGPORT=${PGPORT:-5432}
      - PGDATABASE=${PGDATABASE:-videoshare}
      
      # Security
      - SESSION_SECRET=${SESSION_SECRET:-supersecretkey}
      
      # Storage
      - UPLOAD_FOLDER=${UPLOAD_FOLDER:-/app/uploads}
      - MAX_CONTENT_LENGTH=${MAX_CONTENT_LENGTH:-1073741824}
      
      # App configuration
      - FLASK_APP=${FLASK_APP:-main.py}
      - FLASK_ENV=${FLASK_ENV:-production}
      - SERVER_NAME=${SERVER_NAME:-localhost:5000}
      
      # Video Processing
      - MAX_VIDEOS_PER_USER=${MAX_VIDEOS_PER_USER:-50}
      - CONCURRENT_PROCESSING=${CONCURRENT_PROCESSING:-1}
      
      # yt-dlp configuration
      - YT_DLP_PROXY=${YT_DLP_PROXY:-}
      - YT_DLP_RATE_LIMIT=${YT_DLP_RATE_LIMIT:-500K}
      - YT_DLP_MAX_DURATION=${YT_DLP_MAX_DURATION:-3600}
      
      # Add yt-dlp to PATH
      - PATH=/app/bin:/usr/local/bin:/usr/bin:/bin
      
    volumes:
      - ${LOCAL_UPLOAD_PATH:-./uploads}:${UPLOAD_FOLDER:-/app/uploads}
      - ./emergency_install_ytdlp.py:/app/emergency_install_ytdlp.py
      
    # Simple entrypoint with minimal syntax
    command: >
      bash -c "
        # Ensure clean start - remove any existing symlink to prevent circular issues
        mkdir -p /app/bin
        if [ -L '/app/bin/yt-dlp' ]; then
          echo 'Removing existing symlink /app/bin/yt-dlp to prevent circular references'
          rm -f /app/bin/yt-dlp
        fi
        
        # Install with our python script that fixes circular symlinks
        python /app/emergency_install_ytdlp.py
        
        # Verify installation - this should never be a symlink to itself
        echo 'Verifying yt-dlp installation:'
        file /app/bin/yt-dlp
        
        # Start the application
        python migrations.py && 
        gunicorn --bind 0.0.0.0:5000 --workers 4 main:app
      "
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - videoshare-network

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_PASSWORD=${PGPASSWORD:-postgres}
      - POSTGRES_USER=${PGUSER:-postgres}
      - POSTGRES_DB=${PGDATABASE:-videoshare}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - videoshare-network

networks:
  videoshare-network:
    driver: bridge

volumes:
  postgres_data: {}