version: '3'

services:
  web:
    build: .
    ports:
      - "${PORT:-5000}:5000"
    environment:
      # Database configuration
      - DATABASE_URL=${DATABASE_URL:-postgresql://postgres:postgres@db:5432/videoshare}
      - PGUSER=${PGUSER:-postgres}
      - PGPASSWORD=${PGPASSWORD:-postgres}
      - PGHOST=${PGHOST:-db}
      - PGPORT=${PGPORT:-5432}
      - PGDATABASE=${PGDATABASE:-videoshare}
      
      # Security
      - SESSION_SECRET=${SESSION_SECRET}
      
      # Storage
      - UPLOAD_FOLDER=${UPLOAD_FOLDER:-/app/uploads}
      - MAX_CONTENT_LENGTH=${MAX_CONTENT_LENGTH:-1073741824}
      
      # App configuration
      - FLASK_APP=${FLASK_APP:-main.py}
      - FLASK_ENV=${FLASK_ENV:-production}
      - SERVER_NAME=${SERVER_NAME:-localhost:5000}
      
      # Video Processing
      - MAX_VIDEOS_PER_USER=${MAX_VIDEOS_PER_USER:-50}
      - CONCURRENT_PROCESSING=${CONCURRENT_PROCESSING:-1}
      
      # yt-dlp configuration
      - YT_DLP_PROXY=${YT_DLP_PROXY:-}
      - YT_DLP_RATE_LIMIT=${YT_DLP_RATE_LIMIT:-500K}
      - YT_DLP_MAX_DURATION=${YT_DLP_MAX_DURATION:-3600}
      
      # Add yt-dlp to PATH
      - PATH=/app/bin:/usr/local/bin:/usr/bin:/bin
      
      # For Nginx/proxy configuration (optional)
      - VIRTUAL_HOST=${VIRTUAL_HOST:-}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST:-}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL:-}
    volumes:
      - ${LOCAL_UPLOAD_PATH:-./uploads}:${UPLOAD_FOLDER:-/app/uploads}
      # Mount the installation script
      - ./docker-install-ytdlp.sh:/app/docker-install-ytdlp.sh
      
      # If using Dockge/stacks, uncomment ONE of these options:
      # Option 1: Mount host yt-dlp binary directly
      #- /opt/stacks/nickclips/bin/yt-dlp:/app/bin/yt-dlp
      
      # Option 2: Create a bind mount for the bin directory
      #- ytdlp_data:/app/bin

    # Run an entrypoint script that installs yt-dlp before starting the application
    entrypoint: >
      /bin/bash -c "
        # Make sure bin directory exists
        mkdir -p /app/bin
        
        # Install yt-dlp if it doesn't exist
        if [ ! -x /app/bin/yt-dlp ]; then
          echo 'Installing yt-dlp...'
          chmod +x /app/docker-install-ytdlp.sh
          /app/docker-install-ytdlp.sh
        fi
        
        # Continue with normal startup
        python migrations.py && 
        gunicorn --bind 0.0.0.0:5000 --workers 4 main:app
      "
    depends_on:
      - db
    restart: unless-stopped
    # For Cloudflare Tunnel integration  
    networks:
      - videoshare-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.videoshare.rule=Host(`${DOMAIN:-localhost}`)"
      - "traefik.http.routers.videoshare.entrypoints=websecure"
      - "traefik.http.routers.videoshare.tls=true"

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_PASSWORD=${PGPASSWORD:-postgres}
      - POSTGRES_USER=${PGUSER:-postgres}
      - POSTGRES_DB=${PGDATABASE:-videoshare}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - videoshare-network

networks:
  videoshare-network:
    driver: bridge

volumes:
  postgres_data:
  ytdlp_data:
    # Use this for yt-dlp installations that you want to persist
    # If you uncomment the ytdlp_data volume mount above